/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as VisionRouteImport } from './routes/vision'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesMontageVideoRouteImport } from './routes/services.montage-video'
import { Route as ServicesPublicitesRouteImport } from './routes/services.publicites'
import { Route as ServicesSitesWebRouteImport } from './routes/services.sites-web'
import { Route as ServicesUgcIaRouteImport } from './routes/services.ugc-ia'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const VisionRoute = VisionRouteImport.update({
  id: '/vision',
  path: '/vision',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesMontageVideoRoute = ServicesMontageVideoRouteImport.update({
  id: '/services/montage-video',
  path: '/services/montage-video',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesPublicitesRoute = ServicesPublicitesRouteImport.update({
  id: '/services/publicites',
  path: '/services/publicites',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSitesWebRoute = ServicesSitesWebRouteImport.update({
  id: '/services/sites-web',
  path: '/services/sites-web',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesUgcIaRoute = ServicesUgcIaRouteImport.update({
  id: '/services/ugc-ia',
  path: '/services/ugc-ia',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/portfolio': typeof PortfolioRoute
  '/vision': typeof VisionRoute
  '/services/montage-video': typeof ServicesMontageVideoRoute
  '/services/publicites': typeof ServicesPublicitesRoute
  '/services/sites-web': typeof ServicesSitesWebRoute
  '/services/ugc-ia': typeof ServicesUgcIaRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/portfolio': typeof PortfolioRoute
  '/vision': typeof VisionRoute
  '/services/montage-video': typeof ServicesMontageVideoRoute
  '/services/publicites': typeof ServicesPublicitesRoute
  '/services/sites-web': typeof ServicesSitesWebRoute
  '/services/ugc-ia': typeof ServicesUgcIaRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/portfolio': typeof PortfolioRoute
  '/vision': typeof VisionRoute
  '/services/montage-video': typeof ServicesMontageVideoRoute
  '/services/publicites': typeof ServicesPublicitesRoute
  '/services/sites-web': typeof ServicesSitesWebRoute
  '/services/ugc-ia': typeof ServicesUgcIaRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/portfolio'
    | '/vision'
    | '/services/montage-video'
    | '/services/publicites'
    | '/services/sites-web'
    | '/services/ugc-ia'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/portfolio'
    | '/vision'
    | '/services/montage-video'
    | '/services/publicites'
    | '/services/sites-web'
    | '/services/ugc-ia'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/portfolio'
    | '/vision'
    | '/services/montage-video'
    | '/services/publicites'
    | '/services/sites-web'
    | '/services/ugc-ia'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  PortfolioRoute: typeof PortfolioRoute
  VisionRoute: typeof VisionRoute
  ServicesMontageVideoRoute: typeof ServicesMontageVideoRoute
  ServicesPublicitesRoute: typeof ServicesPublicitesRoute
  ServicesSitesWebRoute: typeof ServicesSitesWebRoute
  ServicesUgcIaRoute: typeof ServicesUgcIaRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vision': {
      id: '/vision'
      path: '/vision'
      fullPath: '/vision'
      preLoaderRoute: typeof VisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/montage-video': {
      id: '/services/montage-video'
      path: '/services/montage-video'
      fullPath: '/services/montage-video'
      preLoaderRoute: typeof ServicesMontageVideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/publicites': {
      id: '/services/publicites'
      path: '/services/publicites'
      fullPath: '/services/publicites'
      preLoaderRoute: typeof ServicesPublicitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/sites-web': {
      id: '/services/sites-web'
      path: '/services/sites-web'
      fullPath: '/services/sites-web'
      preLoaderRoute: typeof ServicesSitesWebRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/ugc-ia': {
      id: '/services/ugc-ia'
      path: '/services/ugc-ia'
      fullPath: '/services/ugc-ia'
      preLoaderRoute: typeof ServicesUgcIaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  PortfolioRoute: PortfolioRoute,
  VisionRoute: VisionRoute,
  ServicesMontageVideoRoute: ServicesMontageVideoRoute,
  ServicesPublicitesRoute: ServicesPublicitesRoute,
  ServicesSitesWebRoute: ServicesSitesWebRoute,
  ServicesUgcIaRoute: ServicesUgcIaRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
